objects/Case_Product__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Products</relationshipLabel>
        <relationshipName>Case_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Product</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Case_Product_Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

classes/QueueableAddOrderItems.cls
public class QueueableAddOrderItems implements Queueable {
    private List<Order> orders;
	private List<OrderItem> orderItems;
    private List<Order> ordersToUpdate;
    
    public QueueableAddOrderItems(List<Order> orders) {
        this.orders = orders;
        this.orderItems = new List<OrderItem>();
        this.ordersToUpdate = new List<Order>();
    }

    public void execute(QueueableContext context) {
        
        // Get related Cases so that we can find the products from case product relationship
        Set<Id> caseIds = new Set<Id>();
        for (Order o : orders) {
            caseIds.add(o.Case__c);
        }
        
        // Another validation to make sure these orders have cases
        if (caseIds.isEmpty()) {
            System.debug(LoggingLevel.INFO, 'No related Case IDs found, exiting QueueableAddOrderItems.');
            return;
        }
        
        //SOQL to get the case product data and store it in a map for easy lookup in order loop
        //This is where it would have been nice to already have the pricebookentry on the case products
        List<Case_Product__c> caseProductsList = [
            SELECT Id, Case__c, Product__c, Quantity__c, Unit_Price__c 
            FROM Case_Product__c 
            WHERE Case__c IN :caseIds
        
        ];
		
        // Map of the products and set of product Ids for the pricebook lookup later
        Map<Id, List<Case_Product__c>> caseProductsMap = new Map<Id, List<Case_Product__c>>();
        Set<Id> productIds = new Set<Id>();
        
        for (Case_Product__c cp : caseProductsList) {
            // Since Cases can have more than one product just making sure it's handled correctly
            if (!caseProductsMap.containsKey(cp.Case__c)) {
                caseProductsMap.put(cp.Case__c, new List<Case_Product__c>());
            }
            caseProductsMap.get(cp.Case__c).add(cp);
            productIds.add(cp.Product__c);
        }
        
        // Now querying the pricebook entry with that list of productIds
        // Again unneeded if I setup the pricebooketnry on the case products 
        Map<Id, Id> productToPricebookEntryMap = new Map<Id, Id>();
		List<PricebookEntry> PricebookEntryList = [
            	SELECT Id, Product2Id 
            	FROM PricebookEntry 
            	WHERE Product2Id IN :productIds AND Pricebook2.IsStandard = TRUE
        ];
        
        for (PricebookEntry pbe : PricebookEntryList) {
        	productToPricebookEntryMap.put(pbe.Product2Id, pbe.Id);
        }
        
        // Loop over the orders to create the order items with the map we created of case product.
        for (Order o : orders) {
            
            if (caseProductsMap.containsKey(o.Case__c)) {
                List<Case_Product__c> caseProducts = caseProductsMap.get(o.Case__c);
                for (Case_Product__c cp : caseProducts) {
                   
                    orderItems.add(new OrderItem(
                        OrderId = o.Id,
                        Product2Id = cp.Product__c,
                        Quantity = cp.Quantity__c,
                        UnitPrice = cp.Unit_Price__c,
                        PricebookEntryId = productToPricebookEntryMap.get(cp.Product__c)
                    ));
                }
            }
            
            // Update Order status
            o.Status = 'Activated';
            ordersToUpdate.add(o);
        }

        if (!orderItems.isEmpty()) {
            insert orderItems;
        }

        if (!ordersToUpdate.isEmpty()) {
            update ordersToUpdate;
        }
    }
}